sudo: required

language: python

services:
  - docker

python:
  - "3.7-dev"

before_install:
- docker-compose build
- docker-compose up -d

script:
  - docker-compose exec solution pytest -s tests.py
