version: '3'
services:
  postgres:
    image: 'postgres:10.1-alpine'
    expose:
      - "5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
  solution:
    entrypoint: /bin/bash
    tty: true
    restart: always
    build: .
    depends_on:
      - postgres
    environment:
      DATABASE_URL: "postgresql://postgres:postgres@postgres:5432/postgres"
